github.com:
    users:
        7Am1:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: 7Am1
